### ISSUE TITLE
Bad parsing of advanced options in classification V2 causes the prediction to fail

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#177]
In the "Classifier settings" screen, the "Custom Settings" contains 

```
posttaxomapping=
usemodel_foldername=testln1
```

which is not parsed correctly and in the log gives

```
2018-05-18 00:25:40,944 - root - INFO - Execute SPCommon for Automatic Classification Task 11515
2018-05-18 00:25:40,945 - root - INFO - Input Param = {'steperrors': [], 'TargetTaxo': '', 'Methode': 'randomforest', 'BaseProject': '847', 'CustSettings': {'posttaxomapping': '', 'usemodel_foldername': 'testln1'}, 'learninglimit': '', 'ProjectId': '847', 'Perimeter': 'nmc', 'Taxo': '12838,30815,26524,81916,45067,11516,78159,84963,45048,11514,25944,92139,45072,85123,85128,51383,45074,28189,51237,85345,92094', 'CritVar': '%area,angle,area,area_exc,bx,by,cdexc,centroids,circ.,circex,convarea,convperim,cv,elongation,esd,fcons,feret,feretareaexc,fractal,height,histcum1,histcum2,histcum3,intden,kurt,major,max,mean,meanpos,median,min,minor,mode,nb1,nb2,perim.,perimareaexc,perimferet,perimmajor,range,skelarea,skew,slope,sr,stddev,symetrieh,symetriehc,symetriev,symetrievc,thickr,width,x,xm,xstart,y,ym,ystart', 'keeplog': 'no', 'resetpredicted': ''}
2018-05-18 00:25:40,945 - root - INFO - Start Step 1
2018-05-18 00:25:40,960 - root - INFO - MapPrj {'kurt': 'n26', 'intden': 'n23', 'symetriehc': 'n50', 'cv': 'n62', 'circex': 'n68', 'elongation': 'n58', 'compentropy': 'n42', 'xmg5': 'n37', 'lon_end': 'n02', 'esd': 'n57', 'perim.': 'n13', 'convarea': 'n53', 'meanpos': 'n60', 'min': 'n07', 'compslope': 'n44', 'feret': 'n22', 'depth_max': 'depth_max', 'centroids': 'n61', 'cdexc': 'n69', 'mean': 'n04', 'mode': 'n06', 'tag': 'n56', 'slope': 'n33', 'skew': 'n25', 'perimmajor': 'n67', 'symetrievc': 'n51', 'perimareaexc': 'n64', 'area': 'n03', 'skelarea': 'n32', 'x': 'n09', 'symetrieh': 'n48', 'feretareaexc': 'n65', 'angle': 'n20', 'xm': 'n11', 'nb2': 'n40', 'height': 'n17', 'histcum1': 'n34', 'histcum3': 'n36', 'perimferet': 'n66', '%area': 'n27', 'minor': 'n19', 'major': 'n18', 'nb3': 'n41', 'symetriev': 'n49', 'compm2': 'n46', 'convperim': 'n52', 'bx': 'n14', 'median': 'n24', 'compm3': 'n47', 'y': 'n10', 'lat_end': 'n01', 'by': 'n15', 'area_exc': 'n30', 'histcum2': 'n35', 'nb1': 'n39', 'xstart': 'n28', 'ym': 'n12', 'fractal': 'n31', 'compm1': 'n45', 'ystart': 'n29', 'thickr': 'n55', 'stddev': 'n05', 'compmean': 'n43', 'sr': 'n63', 'range': 'n59', 'max': 'n08', 'fcons': 'n54', 'circ.': 'n21', 'ymg5': 'n38', 'width': 'n16', 'depth_min': 'depth_min'}
2018-05-18 00:25:40,960 - root - INFO - MapPrjBase {'kurt': 'n26', 'intden': 'n23', 'symetriehc': 'n50', 'cv': 'n62', 'circex': 'n68', 'elongation': 'n58', 'compentropy': 'n42', 'xmg5': 'n37', 'lon_end': 'n02', 'esd': 'n57', 'perim.': 'n13', 'convarea': 'n53', 'meanpos': 'n60', 'min': 'n07', 'compslope': 'n44', 'feret': 'n22', 'depth_max': 'depth_max', 'centroids': 'n61', 'cdexc': 'n69', 'mean': 'n04', 'mode': 'n06', 'tag': 'n56', 'slope': 'n33', 'skew': 'n25', 'perimmajor': 'n67', 'symetrievc': 'n51', 'perimareaexc': 'n64', 'area': 'n03', 'skelarea': 'n32', 'x': 'n09', 'symetrieh': 'n48', 'feretareaexc': 'n65', 'angle': 'n20', 'xm': 'n11', 'nb2': 'n40', 'height': 'n17', 'histcum1': 'n34', 'histcum3': 'n36', 'perimferet': 'n66', '%area': 'n27', 'minor': 'n19', 'major': 'n18', 'nb3': 'n41', 'symetriev': 'n49', 'compm2': 'n46', 'convperim': 'n52', 'bx': 'n14', 'median': 'n24', 'compm3': 'n47', 'y': 'n10', 'lat_end': 'n01', 'by': 'n15', 'area_exc': 'n30', 'histcum2': 'n35', 'nb1': 'n39', 'xstart': 'n28', 'ym': 'n12', 'fractal': 'n31', 'compm1': 'n45', 'ystart': 'n29', 'thickr': 'n55', 'stddev': 'n05', 'compmean': 'n43', 'sr': 'n63', 'range': 'n59', 'max': 'n08', 'fcons': 'n54', 'circ.': 'n21', 'ymg5': 'n38', 'width': 'n16', 'depth_min': 'depth_min'}
2018-05-18 00:25:40,976 - root - ERROR - Unhandled SubProcess Exception
Traceback (most recent call last):
  File "/home/ecotaxa/ecotaxa/runtask.py", line 46, in <module>
    fct()
  File "/home/ecotaxa/ecotaxa/appli/tasks/taskclassifauto.py", line 58, in SPStep1
    PostTaxoMapping = {int(el[0].strip()):int(el[1].strip()) for el in [el.split(':') for el in self.param.CustSettings['posttaxomapping'].split(',')]}
  File "/home/ecotaxa/ecotaxa/appli/tasks/taskclassifauto.py", line 58, in <dictcomp>
    PostTaxoMapping = {int(el[0].strip()):int(el[1].strip()) for el in [el.split(':') for el in self.param.CustSettings['posttaxomapping'].split(',')]}
IndexError: list index out of range
```

**Comment by grololo06** [comment]
This piece of code seems deprecated? It tried in V2 and got no failure:
 'CustSettings': {'posttaxomapping': '', 'usemodel_foldername': 'testln1'}
Shall we close?
