### ISSUE TITLE
IMPORT: bug quand import de lat/lon et pas time

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#243]
```
[...]
2018-07-07 02:23:58,896 - root - ERROR - Unhandled SubProcess Exception
Traceback (most recent call last):
  File "/home/ecotaxa/ecotaxa/runtask.py", line 46, in <module>
    fct()
  File "/home/ecotaxa/ecotaxa/appli/tasks/taskimport.py", line 298, in SPStep1
    self.SPStep2()
  File "/home/ecotaxa/ecotaxa/appli/tasks/taskimport.py", line 409, in SPStep2
    AstralCache['r'] = appli.CalcAstralDayTime(AstralCache['date'], AstralCache['time'], AstralCache['lat'], AstralCache['long'])
  File "/home/ecotaxa/ecotaxa/appli/__init__.py", line 205, in CalcAstralDayTime
    if s[I['d']].time()<s[I['f']].time() and (Time>=s[I['d']].time() and Time<=s[I['f']].time() ) :
TypeError: unorderable types: NoneType() >= datetime.time()
```

Fichiers test joints.
[import avec date.zip](https://github.com/oceanomics/ecotaxa_dev/files/2172280/import.avec.date.zip)
[import sans date.zip](https://github.com/oceanomics/ecotaxa_dev/files/2172281/import.sans.date.zip)

PS: Il faudrait faire une banque de tests avec des cas tordus tels que ceux-ci afin d'éviter les régressions.

**Comment by picheral** [comment]
VALIDE
