### ISSUE TITLE
EcoPart: cannot export restricted project when user is not annotator

### ISSUE THREAD

**Issue by jiho** [oceanomics/ecotaxa_dev#300]
EcoPart project: NAAMES 02
Status: Exportable (orange)

When performing a detailed export by a user who is not registered or only registered as viewer on the corresponding EcoTaxa project, the export fails with the error:

```
2019-02-27 21:55:43,820 - root - INFO - sqllstcat = select distinct classif_id from part_histocat hc where psampleid in ( )  
                            
2019-02-27 21:55:43,821 - flask.app - DEBUG - GetAll Exception SQL = select distinct classif_id from part_histocat hc where psampleid in ( )  
                             None
2019-02-27 21:55:43,828 - root - ERROR - Unhandled SubProcess Exception
Traceback (most recent call last):
  File "/home/ecotaxa/ecotaxa/runtask.py", line 46, in <module>
    fct()
  File "/home/ecotaxa/ecotaxa/appli/tasks/taskpartexport.py", line 768, in SPStep1
    self.CreateDET()
  File "/home/ecotaxa/ecotaxa/appli/tasks/taskpartexport.py", line 458, in CreateDET
    lstcatwhere = GetAll(sqllstcat)
  File "/home/ecotaxa/ecotaxa/appli/database.py", line 421, in GetAll
    cur.execute(sql,params)
  File "/home/ecotaxa/venv_ecotaxa/lib/python3.6/site-packages/psycopg2/extras.py", line 141, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.ProgrammingError: ERREUR:  erreur de syntaxe sur ou près de « ) »
LINE 1: ...ct classif_id from part_histocat hc where psampleid in ( )  
```

It should succeed but exclude the plankton data.

When the user is annotator or manager of the EcoTaxa project, it works.

**Comment by jiho** [comment]
EcoPart project: NAAMES 03
Status: Restricted (red)

When performing a reduced export, with *no* zooplankton group selected, by a user who is not registered or only registered as viewer on the corresponding EcoTaxa project, the export fails with the error:

```
2019-02-27 22:04:34,337 - flask.app - DEBUG - GetAll Exception SQL = SELECT  p.cruise,s.stationid site,s.profileid station,'HDR'||s.filename rawfilename
                        ,p.instrumtype ,s.instrumsn,coalesce(ctd_origfilename,'') ctd_origfilename
                        ,to_char(s.sampledate,'YYYY-MM-DD HH24:MI:SS') sampledate,concat(p.do_name,'(',do_email,')') dataowner
                        ,s.latitude,s.longitude,s.psampleid,s.acq_pixel,acq_aa,acq_exp
                        from part_samples s
                        join part_projects p on s.pprojid = p.pprojid
                        where s.psampleid in ()
                        order by s.profileid
                         None
2019-02-27 22:04:34,343 - root - ERROR - Unhandled SubProcess Exception
Traceback (most recent call last):
  File "/home/ecotaxa/ecotaxa/runtask.py", line 46, in <module>
    fct()
  File "/home/ecotaxa/ecotaxa/appli/tasks/taskpartexport.py", line 766, in SPStep1
    self.CreateRED()
  File "/home/ecotaxa/ecotaxa/appli/tasks/taskpartexport.py", line 73, in CreateRED
    samples=self.GetSamples()
  File "/home/ecotaxa/ecotaxa/appli/tasks/taskpartexport.py", line 59, in GetSamples
    samples=database.GetAll(sql)
  File "/home/ecotaxa/ecotaxa/appli/database.py", line 421, in GetAll
    cur.execute(sql,params)
  File "/home/ecotaxa/venv_ecotaxa/lib/python3.6/site-packages/psycopg2/extras.py", line 141, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.ProgrammingError: ERREUR:  erreur de syntaxe sur ou près de « ) »
LINE 7:                         where s.psampleid in ()
                                                      ^
```
It should succeed but exclude the plankton data.

When the user is annotator or manager of the EcoTaxa project, it works.

**Comment by picheral** [comment]
Ce comportement est conforme à ce qui était spécifié... mais cela ne devrait pas produire d'erreur, seulement un message indiquant qu'on doit demander la permission au project manager du projet EcoTaxa associé.
Le problème persiste pour les projets EcoPart qui ne seraient pas associés à des projets Ecotaxa. QUE FAIT-ON ? Mon opinion est que l'export LPM devrait aboutir en reduced comme en détaillé si la date de rétention est dépassée.

**Comment by grololo06** [comment]
Vu dans les logs du 07/04/2020. L'utilisatrice (Anna Rufas Blanco) a passé l'heure qui suit à faire 17 exports, méthode de contournement du problème?
