### ISSUE TITLE
Python exception when importing a TSV with unknown type (line 2)

### ISSUE THREAD

**Issue by grololo06** [oceanomics/ecotaxa_dev#351]
See https://ecotaxa.obs-vlfr.fr/Task/Show/30672?log=Y

In case the log is gone, it says:
```
  File "/home/ecotaxa/ecotaxa/appli/tasks/taskimport.py", line 131, in SPStep1
    self.LogErrorForUser("Invalid Type '%s' for Field '%s' in file %s. Incorrect Type. Field ignored"%(LType[champ],ColName,relname.as_posix()))
```

The TSV file has, extract of first lines:
```
NoUnderscoreCol        unknown_target      object_wrongtype   object_buggy_float	
                                           [H]                [f]
```

The first erroneous columns correctly end up in error messages, but the 3rd one gives python exception.

**Comment by grololo06** [comment]
The example taks is gone, so copy/paste of a recent similar failure:

```
2020-04-27 05:15:03,960 - root - ERROR - Unhandled SubProcess Exception
Traceback (most recent call last):
  File "/home/ecotaxa/ecotaxa/runtask.py", line 46, in <module>
    fct()
  File "/home/ecotaxa/ecotaxa/appli/tasks/taskimport.py", line 157, in SPStep1
    self.LogErrorForUser("Invalid Type '%s' for Field '%s' in file %s. Incorrect Type. Field ignored"%(LType[champ],ColName,relname.as_posix()))
UnboundLocalError: local variable 'champ' referenced before assignment
```
