### ISSUE TITLE
Python errors in log files related to manual classification

### ISSUE THREAD

**Issue by grololo06** [oceanomics/ecotaxa_dev#418]
Seen in logs while investigating #391:

`[2020-04-06 22:50:26,429] ERROR in __init__: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "/home/ecotaxa/venv_ecotaxa/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ecotaxa/venv_ecotaxa/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ecotaxa/venv_ecotaxa/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "./appli/project/ajaxprocess.py", line 54, in PrjManualClassif
    ,'id':int(v),'qual':gvp('qual')})
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
`
It looks like when saving manual classification, sometimes this failure prevents effective write to DB.

In logs (which start in jan 2019), 195 calls failed (http code 500) when 321457 succeded (http code 200).

**Comment by grololo06** [comment]
Was due to validation of vignette without category. Fixed in v2.3.3
